# Generated by Django 5.2.1 on 2025-06-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('dui', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cotizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRepuestoCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizacion.cotizacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuesto.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('transmision', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('cotizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='cotizacion.cotizante')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.vehiculocotizacion'),
        ),
    ]
