# Generated by Django 5.2.1 on 2025-06-12 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_alter_cotizacion_cotizante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cotizante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizacion.vehiculocotizacion'),
        ),
    ]
