# Generated by Django 5.2.1 on 2025-06-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dui', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('clave', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
